### ISSUE TITLE
Conflicts with Origins Forge

### ISSUE THREAD

**Issue by izzyjeezy** [OhHeyItsJosh/Elytra-Physics#3]
When you start with Origins your game crashes

Origins Forge 1.10.0.2
Elytra Physics 2.0 (Forge)
NeoForge 47.1.79
[crash-2023-11-16_00.34.29-client.txt](https://github.com/OhHeyItsJosh/Elytra-Physics/files/13368916/crash-2023-11-16_00.34.29-client.txt)

**Comment by OhHeyItsJosh** [comment]
I will try and look into this at some point.

**Comment by OhHeyItsJosh** [comment]
Apologies for the long wait,
This should now be resolved in the latest version (2.1).
