### ISSUE TITLE
Elytras worn in the trinkets slot are not affected by physics

### ISSUE THREAD

**Issue by pycuda** [OhHeyItsJosh/Elytra-Physics#4]
This is the mod I used https://modrinth.com/mod/elytra_trinket

**Comment by OhHeyItsJosh** [comment]
There are details on how to add compatability for other mods in the readme for this mod. In this case, you would have to add "pw.lakuna.elytra_trinket.ElytraTrinketFeatureRenderer" to the "inject_layers" in the config.
