### ISSUE TITLE
Compatibility with 'Elytra Trinket'

### ISSUE THREAD

**Issue by el-germi** [OhHeyItsJosh/Elytra-Physics#5]
Enhancement: to add compatibility with <a href="https://modrinth.com/mod/elytra_trinket">Elytra Trinket</a> by default you could add "pw.lakuna.elytra_trinket.ElytraTrinketFeatureRenderer" to the defaultConfig.json inject_layers

**Comment by OhHeyItsJosh** [comment]
This has now been added to the default config as of version 2.1.
